### ISSUE TITLE
Please let us directly type in the intended # of output items.

### ISSUE THREAD

**Issue by Cheddarbeard** [satisfactory-accounting/satisfactory-accounting#12]
I know it's a little outside the original intended purpose for this tool, however it would be quite convenient if it would allow us to adjust not only the # of buildings or the clockspeed... but also let us type in directly the intended # of output items, perhaps with a toggle to hold either the clockspeed or building count static while dynamically adjusting the other?

**Comment by zstewar1** [comment]
Doing the inverse calculation with floating point would be a bit odd, but I am planning some changes that would make this more feasible.

One issue is how to handle output numbers that don't match a whole number of buildings.

I was thinking of adding support for fractional multipliers at least for buildings -- so something like 2.5x would mean 2 buildings at full clock + 1 building at 0.5 clock. I would then have a user setting to choose between "backdrive => set all buildings clocks equally" vs "backdrive => underclock only one building", so if e.g. the number of items you want requires 2.5 buildings, the first would give you 3 buildings all set to 0.833333, while the second option would use the 2.5x multiplier to mean 2 with clock 1.0 + 1 with clock 0.5. The second option would be the default.

There are also a few edge cases that would have to be dealt with, like hitting the limit of the clock speed multiplier, including when combining clock speed with the multiplier clock speed. E.g. if you set a building clock of 1% and then set a multiplier of 2.5x, that should mean 2 @ 1% + 1 @ 0.5%, but thats below the minimum clock speed, so I would have to display a warning and compute as 3 @ 1%

This would probably only apply to individual buildings and not groups. Trying to rebalance a group the match a particular number of output items sounds like a huge pain which would probably not end up working how you want it to anyway.

**Comment by ajur** [comment]
Dunno how others use the tool, but I often use it also for planning. And in those cases, I often find myself having to use calculator for finding clock speed based of how many input/output items I want. But also mingle with number of machines, but thats less painful, and more intentional. 
So, possibility to edit number of input/output materials for group of machines, without changing its number, that would just recalculate the clock, would be awesome. And it would work like in the game - so no changes to number of machines, and just allow to enter any value in range `num of machines * [0.01, 2.5]` :)
And as for backdrive - we can do it currently manually and even put in subfolder to have it grouped.

**Comment by zstewar1** [comment]
I will add support for an initial backdriving mode that calculates a number of machines and clock speed if you type a number of putput items.

The way that makes the most sense to me, at least for things other than miners/extractors, or at least that matches the way I play would be for it to always choose a clock speed <= 1 and use a larger multiplier on the number of buildings to get higher production rates rather than consuming power shards. For miners and extractors, I can see doing the reverse; using higher clock speeds first then adding multiple machines.

Because of limitations in the model this will work by always having a uniform clock speed across all buildings. I will look into non-uniform clock speeds if I get around to some model restructuring that I really want to do.

**Comment by ajur** [comment]
Hmm... maybe some setting for backdrive type (per world, or even per group, or even building type) would be good idea?
- optimize for power usage vs optimize for number of buildings?
Especially you would anyway want to implement both (by default first for all production buildings, and second for miners/extractors).

**Comment by zstewar1** [comment]
In the 1.2.10 update I said I would only add "uniform clock speed" mode, but I then found that adding mixed clock speed support was easier than I expected.

So 1.2.11 will include the ability to set the "multiplier" for a building to a non-integer number, e.g. 3.75, which will mean "3 buildings @ 100% clock + 1 building @ 75% clock". This will multiply with the building's clock speed setting, so if you set a clock speed of 2.0 on that building with a 3.75 multiplier, then it will mean 3@200%+1@150%.

My current plan is to split backdriving settings into 3 groups (normal manufacturers, extraction buildings such as miners, and generators), which each have these same options:

* Uniform clock mode: when backdriving, the chosen multiplier is always an integer and any fractional amount is handled by setting a modified clock speed. The setting will have a box where you can choose a maximum acceptable clock speed, and it will minimize the number of buildings. This will be the default for miners. So for example if you have a normal iron node with a mk2 miner and request 500 ore per minute with a cap of 2.5 clock, it will give you 2 buildings @ 208.3333333% clock. If you set a clock cap of 1.5 and ran it again, it would give 3@138.8888888%
* Mixed clock mode: in this mode, backdriving won't change the clock speed you set on the machine, but it will use the fractional multipliers I mentioned above. This is the default for manufacturing machines including constructors, assemblers, manufacturers, etc. For example, if you have a constructor making iron plate at 100% clock and ask for 110 plate per minute, it will give you a multiplier of 5.5, meaning 5@100% + 1@50%. If you chamge that machine's clock to 200% and run the backdrive again, it would give you a multiplier of 2.75 meaning 2@200% + 1@150%. The clock indicator will show the calculated fractional clock for the last machine so you don't have to do that math yourself.
