### ISSUE TITLE
Save/Load or Import/Export functionality

### ISSUE THREAD

**Issue by TechnoTone** [satisfactory-accounting/satisfactory-accounting#13]
I use multiple computers; it would be helpful to be able to transfer my Accounting between them.
Also, as game saves get bigger or when one has multiple saves, it would be helpful to have different 'Accounts' to work with.

As an aside: I have attempted to download and work on this feature myself, but I have been unsuccessful in getting the projects to build and run. (I'm very inexperienced with the Rust ecosystem but have done a little Rust development.)

**Comment by TechnoTone** [comment]
I've just noticed that the Import/Export functionality has already been suggested (https://github.com/satisfactory-accounting/satisfactory-accounting/issues/7). But I still think a way of saving/loading different 'Accounts' would be useful and separate from that.

**Comment by zstewar1** [comment]
Hi! Sorry, I only just discovered that my github email notifications have been going to spam.

I haven't played Satisfactory in a while and haven't used more than one world yet, so I haven't had much need for this feature. However, I'd be happy to review changes or provide guidance on adding new features. I will see if I can add some build instructions.

Just for basics, the web framework I'm using, Yew, has its own build setup that's separate from normal Rust builds, so I *think* it should work if you follow the Yew setup instructions: https://yew.rs/docs/getting-started/introduction

Specifically, you need to have the `wasm32` target (since it won't build for non-webassembly), and install and use `trunk` as the build tool. If you install `trunk` you should be able to just use `trunk server` for development builds.

For adding multiple "accounts", you'll want to look at the data placed in browser LocalStorage under the keys defined here:
https://github.com/satisfactory-accounting/satisfactory-accounting/blob/master/satisfactory-accounting-app/src/app.rs#L25

Database, Graph, and Metadata are the elements that would make up the state of an "Account".

Database is the production database which defines how much output is produced for any input. I would keep that associated with the "Accounts" in case people run different worlds at different Satisfactory versions, e.g. so updating from U5 to U6 can be done on a per-world (account) basis.

Graph is just the tree of nodes that you use to track production. It includes all your groups and machines and their settings and group names. I does not include the expanded/collapsed state of nodes however.

Metadata stores the expanded/collapsed states of nodes, independently of the actual structure of the tree.

Global Metadata stores user settings like the preference for whether to show or hide empty balances.

Part of the reason database, metadata, and graph are stored in separate keys in local storage rather than together in a single structure is so that I only have to serialize one of them at a time when auto-saving user edits, rather than having to reserialize the whole thing as JSON. For separate accounts, it might not be worth that savings compared to the simplicity of having a single structure for each account. I haven't benchmarked so IDK if it was ever worth doing.

So the simplest approach would be to bundle the database, graph, and metadata into a single `Account` structure for saving/loading purposes and then add a "Current Account" to the `GlobalMetadata` to select which account to show. I would still keep each account separate in LocalStorage (assign them each a UUID or similar) so that we don't have to save/load *all* the accounts whenever we change one of them. So e.g. we could have `GlobalMetadata` contain a `HashMap<AccountId, String>` that just lists the account IDs and account names, and then assign each to a key `zstewart.satisfactorydb.state.account.<AccountId>`. (This example stores the names in global metadata so they can be reached when selecting the current account without having to load the whole thing from JSON LocalStorage just to read that). Maybe I should have used the Indexed DB instead of LocalStorage, but that's a whole separate project.

The name of an account should probably be kept in sync with the name of the Root node of that account. (Maybe instead of storing all the account names in `GlobalMetadata` redundantly, `GlobalMetadata` should store only the `AccountId`s and then the names should be cached in the application when needed by reading all the accounts from storage briefly.

The same `Account` structure could then also be used for Import/Export.

I would also want to keep backwards-compatibility logic: if the account list is empty, check for the current DB_KEY, GRAPH_KEY, METADATA_KEY and create a new account using the existing Database, Graph, and Metadata.

**Comment by zstewar1** [comment]
New release v1.1.0 a9c786d94846664f44aa258709033b6b782ad193 adds the ability to select among several different "Worlds" using the folder icon next to the undo/redo buttons.
