### ISSUE TITLE
Update 6 Recipies

### ISSUE THREAD

**Issue by JasonTGorman** [satisfactory-accounting/satisfactory-accounting#16]
New recipes have been added for Update 6 (e.g. Smokeless Powder). Is it possible to get these recipes updated?

**Comment by zstewar1** [comment]
Have there been any changes to mechanics? E.g. they were talking about changing the math for overclocking at some point.

My recipe database is copied from the one in SatisfactoryTools here: https://github.com/greeny/SatisfactoryTools/blob/u6/data/data.json

I can try pulling their latest recipe database and seeing if my tool to reformat it into the format my system uses still works.

**Comment by JasonTGorman** [comment]
The overclocking changes didn't make it into Update 6.  I know they shifted a whole bunch of things around in the MAM.  The link in your reply does contain the new Smokeless Powder, as well as the new ammunition types (turbo, homing, etc.), but I am unable to select these recipes when using the site.  The data.json file on greeny's page is updated 14 Jun (±4 months ago) with the update 6 recipes.

If I look at the Rifle cartridge I cannot see the turbo or homing ammo type [Turbo Ammo](https://satisfactory.fandom.com/wiki/Rifle#Homing_Ammo), [Homing Ammo](https://satisfactory.fandom.com/wiki/Rifle#Homing_Ammo).

Thanks a lot for helping.

**Comment by zstewar1** [comment]
Well, I can always apply manual patches to the database as needed.

I think I want to make a database selection menu rather than the current setup. Currently when the database for your account is out of date, it just gives a button to update to the latest version, which you can undo initially, but after reloading and losing undo history going back is no longer possible. So I would make a DB selection menu where you can pick exact versions with descriptions.

I'm fairly busy but will try to get to this next week.

**Comment by zstewar1** [comment]
New release v1.1.0 a9c786d94846664f44aa258709033b6b782ad193 adds U6 recipes.
