### ISSUE TITLE
[SUGGESTION] Sort the recipe items in a building so output is left-most item.

### ISSUE THREAD

**Issue by ssaenger** [satisfactory-accounting/satisfactory-accounting#17]
A nice quality update is to sort the NodeDisplay building's entry-row items so that the recipes ingredients are listed first and the product is listed last (to the right). Unfortunately I don't know rust otherwise I'd do a pull request. I do believe though `balance.rs` is responsible for displaying the order of the entry-rows.

**Comment by zstewar1** [comment]
Ah yeah, it always puts power first and then sorts everything else by item, so items always appear in the same order in every list, whether they're an input or an output.

This seems reasonable, but I would want this as a separate option so it doesn't change things unless people want it to. Probably should add a settings menu for this kind of option. Fortunately in the U6 update I did add support for overlay windows, so it should be relatively easy to copy one of those for this.

I also think maybe the sort order should be different for buildings than for groups -- e.g. for large groups, it's probably more useful if the order of items is consistent across groups (easier to eyeball if they always show up in the same order rather than having to scan and see if something is in the + or - group) whereas for buildings you more often want to see quickly what is the inputs and outputs.

However, I'm not sure when I'd have time to get to this, since it's not a priority.

**Comment by ssaenger** [comment]
Thanks for the response. Those are valid thoughts.

That's fair. You do what you want to. I'm making great use of your tool as is :)

**Comment by zstewar1** [comment]
This is implemented in d42f7ac
